PROJECT/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_transactions.urls')),
]

app_transactions/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.register, name='register'),
    path('create/', views.create_transaction, name='create_transaction'),
    path('update/<int:id>/', views.update_transaction, name='update_transaction'),
    path('delete/<int:id>/', views.delete_transaction, name='delete_transaction'),
]

app_transactions/models.py
from django.db import models
from django.contrib.auth.models import User

class Transaction(models.Model):
    TYPE_CHOICES = [
        ('income', 'INCOME +'),
        ('expense', 'EXPENSE -')
    ]
    METHOD_CHOICES = [
        ('card', 'Card'),
        ('cash', 'Cash'),
        ('click', 'Click')
    ]
    
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Amount")
    date = models.DateTimeField(auto_now_add=True)
    type = models.CharField(max_length=7, choices=TYPE_CHOICES, verbose_name="Type")
    method = models.CharField(max_length=5, choices=METHOD_CHOICES, verbose_name="Method")

    def str(self):
        return f"{self.amount} - {self.type} - {self.method}"

app_transactions/forms.py
from django import forms
from .models import Transaction
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class TransactionForm(forms.ModelForm):
    class Meta:
        model = Transaction
        fields = ['amount', 'type', 'method']
        labels = {
            'amount': 'Amount',
            'type': 'Type',
            'method': 'Method'
        }

class CustomUserCreationForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=True, help_text='first_name')
    last_name = forms.CharField(max_length=30, required=True, help_text='last_name')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'password1', 'password2')

app_transactions/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.forms import  AuthenticationForm
from django.contrib.auth.decorators import login_required
from .models import Transaction
from .forms import TransactionForm, CustomUserCreationForm



def home(request):
    if not request.user.is_authenticated:
        return redirect('login')
    transactions = Transaction.objects.filter(user=request.user)
    return render(request, 'app_transactions/home.html', {'transactions': transactions})



def register(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            user.first_name = form.cleaned_data.get('first_name')
            user.last_name = form.cleaned_data.get('last_name')
            user.save()
            login(request, user)
            return redirect('home')
    else:
        form = CustomUserCreationForm()
    return render(request, 'app_transactions/register.html', {'form': form})


def user_login(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('home')
    else:
        form = AuthenticationForm()
    return render(request, 'app_transactions/login.html', {'form': form})


def user_logout(request):
    logout(request)
    return redirect('login')


@login_required
def create_transaction(request):
    if request.method == 'POST':
        form = TransactionForm(request.POST)
        if form.is_valid():
            transaction = form.save(commit=False)
            transaction.user = request.user
            transaction.save()
            return redirect('home')
    else:
        form = TransactionForm()
    return render(request, 'app_transactions/transaction_form.html', {'form': form})


@login_required
def update_transaction(request, id):
    transaction = get_object_or_404(Transaction, id=id, user=request.user)
    if request.method == 'POST':
        form = TransactionForm(request.POST, instance=transaction)
        if form.is_valid():
            form.save()
            return redirect('home')
    else:
        form = TransactionForm(instance=transaction)
    return render(request, 'app_transactions/transaction_form.html', {'form': form})


@login_required
def delete_transaction(request, id):
    transaction = get_object_or_404(Transaction, id=id, user=request.user)
    if request.method == 'POST':
        transaction.delete()
        return redirect('home')
    return render(request, 'app_transactions/confirm_delete.html', {'transaction': transaction})

app_transactions/templates/app_transactions/confirm_delete.html
{% extends 'base_generic.html' %}

{% block title %}Confirm Delete{% endblock %}

{% block content %}
  <h1 class="mb-4">Are you sure you want to delete "{{ transaction.description }}"?</h1>
  <form method="post" class="form">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Yes, delete</button>
  </form>
  <a href="{% url 'home' %}" class="btn btn-secondary mt-2">Cancel</a>
{% endblock %}

app_transactions/templates/app_transactions/home.html
{% extends 'base_generic.html' %}

{% block title %}Home{% endblock %}

{% block content %}

<li class="list-group-item d-flex justify-content-between align-items-center">
  <h3 class="mb-1 text-center">Username: {{ user.username }}</h3>
  {% if request.user.is_superuser %}
  <h3 class="text-xl text-center">Superuser ⭐️⭐️⭐️</h3>
  {% else %}
  <h3 class="text-xl text-center">User ⭐️⭐️</h3>
  {% endif %}
</li>
  <div class="card-header py-3">
  <h1 class="mb-5 text-center">Your transaction page 📈</h1>
  <a href="{% url 'create_transaction' %}" class="btn btn-success mb-4">Create transaction</a>
  <a href="{% url 'login' %}" class="btn btn-danger mb-4 float-right">Log out</a>
  <ul class="list-group">
    {% if transactions %}
      {% for transaction in transactions %}
        <li class="list-group-item d-flex justify-content-between align-items-center">
          {{ transaction.get_type_display }} {{ transaction.amount }} $ - 
          {{ transaction.get_method_display }}🔁 - {{ transaction.date }}🕓
          <div>
            <a href="{% url 'update_transaction' transaction.id %}" class="btn btn-secondary btn-sm">Editing✏️</a>
            <form action="{% url 'delete_transaction' transaction.id %}" method="post" style="display:inline;">
              {% csrf_token %}
              <button type="submit" class="btn btn-danger btn-sm">Delete🗑</button>
            </form>
          </div>
        </li>
      {% endfor %}
    {% else %}
      <p class="border py-3 px-4 text-center">So far there is no transaction ❌</p>
    {% endif %}
  </ul>
  </div>
</div>
</div>
</div>
</div>

{% endblock %}

app_transactions/templates/app_transactions/login.html
{% extends 'base_generic.html' %}

{% block title %}Kirish{% endblock %}

{% block content %}
<div class="container text-center">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <h4>Login page</h4></div>
                <div class="card-body">
                    <form method="post" class="form">
                        {% csrf_token %}
                        <div class="form-group">
                            {{ form.username.label_tag }}
                            {{ form.username }}
                        </div>
                        <div class="form-group">
                            {{ form.password.label_tag }}
                            {{ form.password }}
                        </div>
                        <button type="submit" class="btn btn-primary">Login</button>
                    </form>
                    <a href="{% url 'register' %}" class="mt-3 d-block">Not registered? Click to register</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app_transactions/templates/app_transactions/register.html
{% extends 'base_generic.html' %}

{% block title %}Barcha ma'lumotlaringizni kiriting{% endblock %}

{% block content %}
<div class="container text-center">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header py-3">
                    <h4>Enter your data</h4></div>
                <div class="card-body">
                    <form method="post" class="form">
                        {% csrf_token %}
                        <div class="form-group mb-3">
                            {{ form.username.label_tag }}
                            {{ form.username }}
                        </div>
                        <div class="form-group mb-3">
                            {{ form.first_name.label_tag }}
                            {{ form.first_name }}
                        </div>
                        <div class="form-group mb-3">
                            {{ form.last_name.label_tag }}
                            {{ form.last_name }}
                        </div>
                        <div class="form-group mb-3">
                            {{ form.password1.label_tag }}
                            {{ form.password1 }}
                        </div>
                        <div class="form-group mb-3">
                            {{ form.password2.label_tag }}
                            {{ form.password2 }}
                        </div>
                        <button type="submit" class="btn btn-primary">Sign up</button>
                    </form>
                    <a href="{% url 'login' %}" class="mt-3 d-block">Have you registered? Login</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app_transactions/templates/app_transactions/transaction_form.html
{% extends 'base_generic.html' %}

{% block title %}Tranzaksiya yaratish/tahrirlash{% endblock %}

{% block content %}
<div class="container text-center">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <h3>Creating and editing transaction</h3></div>
                <div class="card-body">
                    <form method="post" class="form">
                        {% csrf_token %}
                        <div class="form-group">
                            {{ form.amount.label_tag }}
                            {{ form.amount }}
                        </div>
                        <div class="form-group">
                            {{ form.type.label_tag }}
                            {{ form.type }}
                        </div>
                        <div class="form-group">
                            {{ form.method.label_tag }}
                            {{ form.method }}
                        </div>
                        <button type="submit" class="btn btn-primary">Storage</button>
                    </form>
                    <a href="{% url 'home' %}" class="btn btn-secondary mt-2">Return to Home↩️</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app_transactions/templates/base_generic.html
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}Transactions{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <style>
        .container {
            margin-top: 50px;
        }
        .navbar-nav {
            flex-direction: row;
        }
        .nav-link {
            padding-right: .5rem;
            padding-left: .5rem;
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'home' %}">Transactions</a>
        <div class="collapse navbar-collapse">
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}">Log out</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'register' %}">Sign up</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>